name: Build iOS
run-name: ${{ github.actor }} is building for Apple App Store
on:
  push:
    branches:
      - releases
      - '*-build'
  workflow_dispatch:
jobs:
  unity-build-ios:
    runs-on: macos-latest
    steps:
      - name: Process cached Unity Installation
        uses: actions/cache@v3
        with:
          path: |
            /Applications/Unity/Hub/Editor/${{ vars.UNITY_VERSION }}
            ~/Library/Application Support/Unity
          key: unity-${{ runner.os }}-${{ vars.UNITY_VERSION }}
          restore-keys: |
            unity-${{ runner.os }}-${{ vars.UNITY_VERSION }}
            unity-${{ runner.os }}-

      - name: Process cached Library folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-
            Library

      - name: Checkout git repo
        uses: actions/checkout@v5

      - name: Generate Unity build for iOS
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
          unityVersion: ${{ vars.UNITY_VERSION }}
          versioning: Semantic

      - name: Upload Unity build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/iOS

  xcode-build-ios:
    runs-on: macos-latest
    needs: unity-build-ios

    steps:
      - name: Download Unity build
        uses: actions/download-artifact@v4
        with:
          name: ios-build
          path: build/iOS

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_P12_FILE_BASE64 }}
          p12-password: ${{ secrets.APPLE_P12_PASSWORD }}

      - name: Install provising profile
        uses: apple-actions/download-provisioning-profiles@v4
        with:
          bundle-id: com.BaconetaStudios.Setting-The-Stage
          profile-type: IOS_APP_STORE
          issuer-id: ${{ secrets.APPLE_API_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_API_PRIVATE_KEY }}

      - name: Generate Xcode build
        run: |
          xcodebuild -project build/iOS/Unity-iPhone.xcodeproj \
          -scheme Unity-iPhone \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath build/Unity.xarchive
      - name: Export Xcode build
        run: |
          xcodebuild -exportArchive \
          -archivePath build/Unity.xarchive \
          -exportOptionsPlist build/iOS/exportOptions.plist \
          -exportPath build
      - name: Upload Xcode build
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/*.ipa
