name: Build Android
run-name: ${{ github.actor }} is building for Google Play
on:
  push:
    branches:
      - releases
      - '*-build'
  workflow_dispatch:
jobs:
  unity-build-android:
    runs-on: ubuntu-latest
    steps:
